#ifndef EVENTS_ID_HPP
#define EVENTS_ID_HPP

#define BUTTON_MINUS_PRESS_EVENT_ID 0x80
#define BUTTON_PLUS_PRESS_EVENT_ID 0x81
#define BUTTON_RUN_PRESS_EVENT_ID 0x82
#define USART_CHAR_RECEIVED_EVENT_ID 0x83
#define TIMER_0_EVENT_ID 0x84
#define TIMER_1_EVENT_ID 0x85
#define TIMER_2_EVENT_ID 0x86
#define TIMER_3_EVENT_ID 0x87

#endif /* EVENTS_ID_HPP */
